// "use client";

// import { motion, useInView } from "framer-motion";
// import { useRef, useState, useEffect } from "react";
// import { Button } from "@/components/common/button";
// import { Input } from "@/components/common/input";
// import { Textarea } from "@/components/common/textarea";
// import { X, PhoneCall } from "lucide-react";
// // import { getPlanMessage } from "./auto-message"
// // import { postLead } from "@/services/service-api/postLeadService"
// // import { postLeadLocal } from "@/services/service-api/postLeadLocalService"
// // import type { getContactInfo } from "@/services/service-api/getContactInfoService"
// import { MOCK_CONTACT } from "@/public/data/mockApi";

// const hearAboutOptions = [
//   "Google Search",
//   "Social Media (Instagram / Facebook / LinkedIn / Twitter)",
//   "YouTube",
//   "Email Newsletter",
//   "Friends / Family (Word of Mouth)",
//   "Existing Customer / Referral",
//   "Online Ads (Google Ads, Facebook Ads, etc.)",
//   "Website / Blog",
//   "Event / Seminar / Conference",
//   "Other",
// ];

// export function ContactForm({ getContact = [] }) {
//   const ref = useRef(null);
//   const isInView = useInView(ref, { once: true, amount: 0.2 });

//   const [formData, setFormData] = useState({
//     name: "",
//     email: "",
//     phone: "",
//     business: "",
//     message: "",
//     hearAbout: "",
//     hearAboutOther: "",
//   });

//   const [showAlert, setShowAlert] = useState(false);
//   const [phoneError, setPhoneError] = useState("");
//   const [emailError, setEmailError] = useState("");
//   const [nameError, setNameError] = useState("");
//   const [hearAboutOtherError, setHearAboutOtherError] = useState("");
//   const [isMessageAutoGenerated, setIsMessageAutoGenerated] = useState(false);

//   const isValidEmail = (email: string) =>
//     /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
//   const isValidName = (name: string) =>
//     /^[a-zA-Z\s]+$/.test(name) && name.trim().length > 0;

//   //   useEffect(() => {
//   //     const handlePlanSelected = (event: CustomEvent) => {
//   //       const { planName } = event.detail
//   //       const autoMessage = getPlanMessage(planName)

//   //       if (autoMessage) {
//   //         setFormData((prev) => ({
//   //           ...prev,
//   //           message: autoMessage,
//   //         }))
//   //         setIsMessageAutoGenerated(true)
//   //       }
//   //     }

//   //     window.addEventListener("planSelected", handlePlanSelected as EventListener)
//   //     return () => {
//   //       window.removeEventListener("planSelected", handlePlanSelected as EventListener)
//   //     }
//   //   }, [])

//   //   const handleSubmit = async (e: React.FormEvent) => {
//   //     e.preventDefault()

//   //     let hasErrors = false
//   //     if (!isValidName(formData.name)) {
//   //       setNameError("Name should contain only letters and spaces")
//   //       hasErrors = true
//   //     }
//   //     if (formData.email && !isValidEmail(formData.email)) {
//   //       setEmailError("Please enter a valid email address")
//   //       hasErrors = true
//   //     }
//   //     if (formData.phone.length !== 10) {
//   //       setPhoneError("Phone number must be exactly 10 digits")
//   //       hasErrors = true
//   //     }
//   //     if (formData.hearAbout === "Other" && !formData.hearAboutOther.trim()) {
//   //       setHearAboutOtherError("Please specify how you heard about us")
//   //       hasErrors = true
//   //     }
//   //     if (hasErrors) return

//   //     try {
//   //       const finalHearAboutValue =
//   //         formData.hearAbout === "Other" ? formData.hearAboutOther.trim() : formData.hearAbout

//   //       // Submit to local SQL Server API
//   //       await postLeadLocal({
//   //         FullName: formData.name,
//   //         EmailAddress: formData.email || "",
//   //         PhoneNumber: formData.phone,
//   //         BusinessName: formData.business || "",
//   //         Message: formData.message,
//   //         WhereDidYouHearAboutUs: finalHearAboutValue,
//   //       })

//   //       setShowAlert(true)
//   //       setFormData({
//   //         name: "",
//   //         email: "",
//   //         phone: "",
//   //         business: "",
//   //         message: "",
//   //         hearAbout: "",
//   //         hearAboutOther: "",
//   //       })
//   //       setPhoneError("")
//   //       setEmailError("")
//   //       setNameError("")
//   //       setHearAboutOtherError("")
//   //       setIsMessageAutoGenerated(false)
//   //     } catch (error) {
//   //       console.error("Error submitting form:", error)
//   //       alert("Something went wrong! Please try again.")
//   //     }
//   //   }

//   const handleChange = (
//     e: React.ChangeEvent<
//       HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
//     >
//   ) => {
//     const { name, value } = e.target;

//     if (name === "name") {
//       if (!/^[a-zA-Z\s]*$/.test(value)) return;
//       setNameError("");
//     }
//     if (name === "email") setEmailError("");
//     if (name === "phone") {
//       if (!/^\d*$/.test(value)) return;
//       if (value.length > 10) return;
//       setPhoneError("");
//     }
//     if (name === "business" && !/^[a-zA-Z0-9\s&.,'-]*$/.test(value)) return;
//     if (name === "hearAboutOther") setHearAboutOtherError("");
//     if (name === "message" && isMessageAutoGenerated)
//       setIsMessageAutoGenerated(false);

//     setFormData({ ...formData, [name]: value });
//   };
//   // --- STYLES DEFINITION FOR SCREENSHOT MATCH ---

//   // Updated placeholder color to explicitly be black (placeholder:text-black)
//   const inputBaseClasses =
//     "w-full text-base border-gray-200 bg-green-50/70 rounded-lg h-11 transition-all duration-300 p-2.5 text-gray placeholder:text-black";
//   // Focus classes for the green border/ring
//   const focusClasses =
//     "focus:border-green-400 focus:ring-2 focus:ring-green-100 focus:outline-none";
//   // Base classes for textarea
//   const textareaBaseClasses =
//     "w-full text-base min-h-[120px] border-gray-200 bg-green-50/70 rounded-lg resize-none transition-all duration-300 p-2.5 text-black placeholder:text-black";
//   return (
//     <section
//       id="contact"
//       ref={ref}
//       className="py-8 sm:py-12 lg:py-16 xl:py-20 px-3 sm:px-4 lg:px-6 xl:px-20 bg-white relative"
//     >
//       <div className="max-w-7xl mx-auto text-center">
//         <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[rgb(6_182_212_/_0.1)] border border-[rgb(6_182_212_/_0.2)] backdrop-blur-sm mb-6">
//           <PhoneCall className="w-4 h-4 text-cyan-600" />
//           <span className="text-sm font-medium text-slate-700">Contact Us</span>
//         </div>

//         <motion.div
//           initial={{ opacity: 0, y: 30 }}
//           whileInView={{ opacity: 1, y: 0 }}
//           viewport={{ once: true }}
//           transition={{ duration: 0.7 }}
//           className="text-center mb-12"
//         >
//           <h2 className="text-4xl lg:text-5xl font-bold mb-3">
//             <span className="text-slate-900">Our </span>
//             <span className="bg-gradient-to-r from-blue-600 to-cyan-500 bg-clip-text text-transparent">
//               Get Started Today
//             </span>
//           </h2>

//           <p className="text-lg text-slate-600">
//             Ready to transform your Business? Contact us for a free demo and
//             consultation.
//           </p>
//         </motion.div>

//         {showAlert && (
//           <div className="fixed inset-0 flex items-center justify-center bg-black/50 z-50 p-3 sm:p-4">
//             <div className="bg-white rounded-xl shadow-lg max-w-sm sm:max-w-md w-full p-4 sm:p-6 relative text-center mx-4">
//               <Button
//                 onClick={() => setShowAlert(false)}
//                 className="absolute top-2 right-2 sm:top-3 sm:right-3 text-gray-400 hover:text-gray-600"
//               >
//                 <X className="w-4 h-4 sm:w-5 sm:h-5" />
//               </Button>
//               <h3 className="text-lg sm:text-xl font-bold text-primary mb-2 sm:mb-3">
//                 Informational Message
//               </h3>
//               <p className="text-sm sm:text-base text-gray-700">
//                 Thank you for your interest! We will contact you soon. <br />
//                 For further inquiry contact us on{" "}
//                 <span className="font-semibold text-primary">8149798679</span>.
//               </p>
//               <Button
//                 onClick={() => setShowAlert(false)}
//                 className="mt-4 sm:mt-6 bg-gradient-to-r from-primary to-primary-dark text-white px-4 sm:px-6 py-2 text-sm sm:text-base rounded-full"
//               >
//                 OK
//               </Button>
//             </div>
//           </div>
//         )}

//         <div className="flex flex-col lg:flex-row gap-6 sm:gap-8 lg:gap-12 items-start">
//           {/* LEFT — CONTACT FORM */}

//           <motion.div
//             initial={{ opacity: 0, x: -30 }}
//             animate={isInView ? { opacity: 1, x: 0 } : {}}
//             transition={{ duration: 0.6, delay: 0.2 }}
//             className="w-full lg:w-1/2 order-2 lg:order-1"
//           >
//             <div className="bg-primary/5 border border-primary/20 rounded-xl sm:rounded-2xl p-4 sm:p-6 lg:p-8 shadow-lg">
//               <h3 className="text-lg sm:text-xl lg:text-2xl font-bold text-gray-900 mb-4 sm:mb-6 text-left">
//                 Send us a Message
//               </h3>

//               {/* <form className="space-y-4 sm:space-y-5 lg:space-y-6">
//                 <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
//                   <div>
//                     <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                       Full Name *
//                     </label>
//                     <Input
//                       name="name"
//                       value={formData.name}
//                       onChange={handleChange}
//                       required
//                       className={`${inputBaseClasses} ${focusClasses} ${
//                         nameError ? "border-red-500" : ""
//                       }`}
//                       placeholder="Enter your full name"
//                     />

//                     {nameError && (
//                       <p className="text-red-500 text-xs sm:text-sm mt-1">
//                         {nameError}
//                       </p>
//                     )}
//                   </div>

//                   <div>
//                     <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                       Email Address
//                     </label>
//                     <Input
//                       name="email"
//                       type="email"
//                       value={formData.email}
//                       onChange={handleChange}
//                       className={`${inputBaseClasses} ${focusClasses} ${
//                         emailError ? "border-red-500" : ""
//                       }`}
//                       placeholder="Enter your email"
//                     />
//                     {emailError && (
//                       <p className="text-red-500 text-xs sm:text-sm mt-1">
//                         {emailError}
//                       </p>
//                     )}
//                   </div>
//                 </div>

//                 <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
//                   <div>
//                     <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                       Phone Number *
//                     </label>
//                     <Input
//                       name="phone"
//                       type="tel"
//                       value={formData.phone}
//                       onChange={handleChange}
//                       required
//                       className={`${inputBaseClasses} ${focusClasses} ${
//                         phoneError ? "border-red-500" : ""
//                       }`}
//                       placeholder="Enter your phone number"
//                     />
//                     {phoneError && (
//                       <p className="text-red-500 text-xs sm:text-sm mt-1">
//                         {phoneError}
//                       </p>
//                     )}
//                   </div>

//                   <div>
//                     <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                       Business Name
//                     </label>
//                     <Input
//                       name="business"
//                       value={formData.business}
//                       onChange={handleChange}
//                       className={`${inputBaseClasses} ${focusClasses}`}
//                       placeholder="Enter your business name"
//                     />
//                   </div>
//                 </div>

//                 <div className="relative">
//                   <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                     Where did you hear about us? *
//                   </label>
//                   <select
//                     name="hearAbout"
//                     value={formData.hearAbout}
//                     onChange={handleChange}
//                     required
//                     className={`
//                       w-full text-sm sm:text-base border border-gray-200 rounded-lg h-11 transition-all duration-300
//                       p-2 sm:p-2.5 bg-green-50/70
//                       ${focusClasses}
//                       text-black appearance-none
//                     `}
//                   >
//                     <option value="" hidden>
//                       Select an option
//                     </option>
//                     {hearAboutOptions.map((option, idx) => (
//                       <option key={idx} value={option}>
//                         {option}
//                       </option>
//                     ))}
//                   </select>

//                   <svg
//                     className="pointer-events-none absolute right-3 top-[50%] transform -translate-y-[50%] h-4 w-4 text-gray-500"
//                     xmlns="http://www.w3.org/2000/svg"
//                     viewBox="0 0 20 20"
//                     fill="currentColor"
//                     aria-hidden="true"
//                   >
//                     <path
//                       fillRule="evenodd"
//                       d="M5.23 7.21a.75.75 0 011.06.02L10 10.94l3.71-3.71a.75.75 0 111.06 1.06l-4.25 4.25a.75.75 0 01-1.06 0L5.21 8.27a.75.75 0 01.02-1.06z"
//                       clipRule="evenodd"
//                     />
//                   </svg>
//                 </div>

//                 {formData.hearAbout === "Other" && (
//                   <div>
//                     <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                       Other (please mention) *
//                     </label>
//                     <Input
//                       name="hearAboutOther"
//                       value={formData.hearAboutOther}
//                       onChange={handleChange}
//                       required

//                       className={`${inputBaseClasses} ${focusClasses} ${
//                         hearAboutOtherError ? "border-red-500" : ""
//                       }`}
//                       placeholder="Enter details..."
//                     />
//                     {hearAboutOtherError && (
//                       <p className="text-red-500 text-xs sm:text-sm mt-1">
//                         {hearAboutOtherError}
//                       </p>
//                     )}
//                   </div>
//                 )}

//                 <div>
//                   <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                     Message *
//                   </label>
//                   <Textarea
//                     name="message"
//                     value={formData.message}
//                     onChange={handleChange}
//                     required
//                     className={`${textareaBaseClasses} ${focusClasses}`}
//                     placeholder="Tell us about your requirements..."
//                   />
//                 </div>

//                 <Button
//                   type="submit"
//                   className="w-full bg-gradient-to-r from-blue-600 to-emerald-500 hover:from-blue-700 hover:to-emerald-600 text-white py-2.5 sm:py-3 text-base sm:text-lg font-semibold rounded-lg shadow-lg transition-all duration-300"
//                 >
//                   Send Message
//                 </Button>
//               </form> */}
//               <form className="space-y-4 sm:space-y-5 lg:space-y-6">
//                 {/* Name + Email */}
//                 <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
//                   {/* Full Name */}
//                   <div>
//                     <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                       Full Name *
//                     </label>

//                     <Input
//                       name="name"
//                       value={formData.name}
//                       onChange={handleChange}
//                       required
//                       className={`${inputBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm ${
//                         nameError ? "border-red-500" : ""
//                       }`}
//                       placeholder="Enter your full name"
//                     />

//                     {nameError && (
//                       <p className="text-red-500 text-xs sm:text-sm mt-1">
//                         {nameError}
//                       </p>
//                     )}
//                   </div>

//                   {/* Email */}
//                   <div>
//                     <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                       Email Address
//                     </label>

//                     <Input
//                       name="email"
//                       type="email"
//                       value={formData.email}
//                       onChange={handleChange}
//                       className={`${inputBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm ${
//                         emailError ? "border-red-500" : ""
//                       }`}
//                       placeholder="Enter your email"
//                     />

//                     {emailError && (
//                       <p className="text-red-500 text-xs sm:text-sm mt-1">
//                         {emailError}
//                       </p>
//                     )}
//                   </div>
//                 </div>

//                 {/* Phone + Business */}
//                 <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
//                   {/* Phone */}
//                   <div>
//                     <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                       Phone Number *
//                     </label>

//                     <Input
//                       name="phone"
//                       type="tel"
//                       value={formData.phone}
//                       onChange={handleChange}
//                       required
//                       className={`${inputBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm ${
//                         phoneError ? "border-red-500" : ""
//                       }`}
//                       placeholder="Enter your phone number"
//                     />

//                     {phoneError && (
//                       <p className="text-red-500 text-xs sm:text-sm mt-1">
//                         {phoneError}
//                       </p>
//                     )}
//                   </div>

//                   {/* Business */}
//                   <div>
//                     <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                       Business Name
//                     </label>

//                     <Input
//                       name="business"
//                       value={formData.business}
//                       onChange={handleChange}
//                       className={`${inputBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm`}
//                       placeholder="Enter your business name"
//                     />
//                   </div>
//                 </div>

//                 {/* Hear About */}
//                 <div className="relative">
//                   <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                     Where did you hear about us? *
//                   </label>

//                   {/* <select
//                     name="hearAbout"
//                     value={formData.hearAbout}
//                     onChange={handleChange}
//                     required
//                     className="
//         w-full text-sm sm:text-base border border-gray-200 rounded-lg h-11
//         transition-all duration-300 p-2 sm:p-2.5 bg-green-50/70
//         text-black appearance-none placeholder:text-xs sm:placeholder:text-sm
//       "
//                   >
//                     <option value="" hidden>
//                       Select an option
//                     </option>

//                     {hearAboutOptions.map((option, idx) => (
//                       <option key={idx} value={option}>
//                         {option}
//                       </option>
//                     ))}
//                   </select> */}
//                   <select
//                     name="hearAbout"
//                     value={formData.hearAbout}
//                     onChange={handleChange}
//                     required
//                     className="
//     w-full text-xs sm:text-sm
//     border border-gray-200 rounded-lg h-11
//     transition-all duration-300 p-2 sm:p-2.5
//     bg-green-50/70 text-black appearance-none
//     placeholder:text-xs sm:placeholder:text-sm
//   "
//                   >
//                     <option value="" hidden>
//                       Select an option
//                     </option>

//                     {hearAboutOptions.map((option, idx) => (
//                       <option key={idx} value={option}>
//                         {option}
//                       </option>
//                     ))}
//                   </select>

//                   <svg
//                     className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500"
//                     xmlns="http://www.w3.org/2000/svg"
//                     viewBox="0 0 20 20"
//                     fill="currentColor"
//                   >
//                     <path
//                       fillRule="evenodd"
//                       d="M5.23 7.21a.75.75 0 011.06.02L10 10.94l3.71-3.71a.75.75 0 111.06 1.06l-4.25 4.25a.75.75 0 01-1.06 0L5.21 8.27a.75.75 0 01.02-1.06z"
//                       clipRule="evenodd"
//                     />
//                   </svg>
//                 </div>

//                 {/* Other */}
//                 {formData.hearAbout === "Other" && (
//                   <div>
//                     <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                       Other (please mention) *
//                     </label>

//                     <Input
//                       name="hearAboutOther"
//                       value={formData.hearAboutOther}
//                       onChange={handleChange}
//                       required
//                       className={`${inputBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm ${
//                         hearAboutOtherError ? "border-red-500" : ""
//                       }`}
//                       placeholder="Enter details..."
//                     />

//                     {hearAboutOtherError && (
//                       <p className="text-red-500 text-xs sm:text-sm mt-1">
//                         {hearAboutOtherError}
//                       </p>
//                     )}
//                   </div>
//                 )}

//                 {/* Message */}
//                 <div>
//                   <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
//                     Message *
//                   </label>

//                   {/* <Textarea
//                     name="message"
//                     value={formData.message}
//                     onChange={handleChange}
//                     required
//                     className={`${textareaBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm`}
//                     placeholder="Tell us about your requirements..."
//                   /> */}
//                   <Textarea
//                     name="message"
//                     value={formData.message}
//                     onChange={handleChange}
//                     required
//                     className={`${textareaBaseClasses} ${focusClasses} text-xs sm:text-sm placeholder:text-xs sm:placeholder:text-sm`}
//                     placeholder="Tell us about your requirements..."
//                   />
//                 </div>

//                 {/* Submit */}
//                 <Button
//                   type="submit"
//                   className="w-full bg-gradient-to-r from-blue-600 to-emerald-500 hover:from-blue-700 hover:to-emerald-600 text-white py-2.5 sm:py-3 text-base sm:text-lg font-semibold rounded-lg shadow-lg transition-all duration-300"
//                 >
//                   Send Message
//                 </Button>
//               </form>
//             </div>
//           </motion.div>
//           {/* RIGHT — CONTACT INFO */}
//           <motion.div
//             initial={{ opacity: 0, x: 30 }}
//             animate={isInView ? { opacity: 1, x: 0 } : {}}
//             transition={{ duration: 0.6, delay: 0.4 }}
//             className="w-full lg:w-1/2 order-1 lg:order-2"
//           >
//             <div className="space-y-3 sm:space-y-4 lg:space-y-5">
//               <div className="text-center">
//                 <h4 className="text-lg sm:text-xl lg:text-xl font-bold text-gray-900 mb-1 sm:mb-2">
//                   Contact Information
//                 </h4>
//               </div>

//               {/* Phone, Email, Support */}
//               <div className="grid grid-cols-3 gap-2 sm:gap-3 lg:gap-4">
//                 {MOCK_CONTACT.filter?.((item) =>
//                   ["Phone", "Email", "Support Hours"].includes(item?.Title)
//                 )?.map?.((item) => {
//                   let details: string[] = [];
//                   try {
//                     details = item.Details1.split(",").map((d) => d.trim());
//                   } catch {
//                     details = [item.Details1];
//                   }

//                   const reorderedDetails =
//                     details.length > 1
//                       ? [details[details.length - 1], ...details.slice(0, -1)]
//                       : details;

//                   return (
//                     <div
//                       key={item.Id}
//                       className="flex flex-col items-center text-center"
//                     >
//                       <div className="p-1.5 sm:p-2 rounded-full bg-primary-light flex items-center justify-center mb-1">
//                         <item.Icon className="h-3 w-3 sm:h-4 sm:w-4" />
//                       </div>
//                       <h5 className="font-semibold text-gray-900 text-xs sm:text-xs mb-0.5">
//                         {item.Title}
//                       </h5>
//                       <div className="text-gray-600 text-[10px] sm:text-xs">
//                         {reorderedDetails.map((d: string, idx) => (
//                           <p key={idx} className="leading-tight break-words">
//                             {d}
//                           </p>
//                         ))}
//                       </div>
//                       {item.Details2 && (
//                         <p className="text-[9px] sm:text-xs text-gray-500 mt-0.5 break-words">
//                           {item.Details2}
//                         </p>
//                       )}
//                     </div>
//                   );
//                 })}
//               </div>

//               {/* Office */}
//               <div className="bg-primary-light rounded-lg p-2 sm:p-2.5 shadow-sm">
//                 {MOCK_CONTACT.filter?.(
//                   (item) => item?.Title === "Office"
//                 )?.map?.((item) => {
//                   let offices: string[] = [];
//                   try {
//                     offices = JSON.parse(item.Details1);
//                   } catch {
//                     offices = [];
//                   }

//                   return (
//                     <div key={item.Id}>
//                       <div className="flex items-center justify-center mb-1.5 sm:mb-2">
//                         <item.Icon className="h-3 w-3 sm:h-4 sm:w-4 mr-1" />
//                         <h5 className="font-semibold text-gray-900 text-xs sm:text-sm">
//                           Office Locations
//                         </h5>
//                       </div>

//                       <div className="grid gap-1">
//                         {offices.map((address, idx) => (
//                           <div
//                             key={idx}
//                             className="bg-white rounded p-1.5 sm:p-2 border-l-2 sm:border-l-3 border-primary"
//                           >
//                             <div className="flex items-start">
//                               <span className="inline-flex items-center justify-center w-3 h-3 sm:w-4 sm:h-4 bg-primary text-white rounded-full text-[8px] sm:text-[9px] font-semibold mr-1.5 mt-0.5 flex-shrink-0">
//                                 {idx + 1}
//                               </span>
//                               <p className="text-gray-700 text-[10px] sm:text-xs leading-tight break-words">
//                                 {address}
//                               </p>
//                             </div>
//                           </div>
//                         ))}
//                       </div>
//                     </div>
//                   );
//                 })}
//               </div>

//               {/* Map */}
//               <div className="bg-primary-light rounded-lg overflow-hidden shadow-md">
//                 {/* <iframe
//                     src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15036.51761826522!2d74.18727!3d19.57895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b887760ab19f%3A0x3fd52e46fe6d323f!2sSoulSoft%20Infotech!5e0!3m2!1sen!2sin!4v1758356538198!5m2!1sen!2sin%22
//                     width="100%"
//                     height="250"
//                     style={{ border: "0" }}
//                     allowFullScreen
//                     loading="lazy"
//                     referrerPolicy="no-referrer-when-downgrade"
//                     className="rounded-lg sm:h-[300px] lg:h-[300px]"
//                     title="SoulSoft Infotech Location"
//                     /> */}
//                 <iframe
//                   src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15036.51761826522!2d74.18727!3d19.57895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b887760ab19f%3A0x3fd52e46fe6d323f!2sSoulSoft%20Infotech!5e0!3m2!1sen!2sin!4v1758356538198!5m2!1sen!2sin"
//                   width="100%"
//                   height="250"
//                   style={{ border: "0" }}
//                   allowFullScreen
//                   loading="lazy"
//                   referrerPolicy="no-referrer-when-downgrade"
//                   className="rounded-lg sm:h-[300px] lg:h-[300px]"
//                   title="SoulSoft Infotech Location"
//                 />
//               </div>
//             </div>
//           </motion.div>
//         </div>
//       </div>
//     </section>
//   );
// }

"use client";

import { motion, useInView } from "framer-motion";
import { useRef, useState, useEffect } from "react";
import { Button } from "@/components/common/button";
import { Input } from "@/components/common/input";
import { Textarea } from "@/components/common/textarea";
import { X, PhoneCall } from "lucide-react";
// import { getPlanMessage } from "./auto-message"
// import { postLead } from "@/services/service-api/postLeadService"
// import { postLeadLocal } from "@/services/service-api/postLeadLocalService"
// import type { getContactInfo } from "@/services/service-api/getContactInfoService"
import { MOCK_CONTACT } from "@/public/data/mockApi";

const hearAboutOptions = [
  "Google Search",
  "Social Media (Instagram / Facebook / LinkedIn / Twitter)",
  "YouTube",
  "Email Newsletter",
  "Friends / Family (Word of Mouth)",
  "Existing Customer / Referral",
  "Online Ads (Google Ads, Facebook Ads, etc.)",
  "Website / Blog",
  "Event / Seminar / Conference",
  "Other",
];

export function ContactForm({ getContact = [] }) {
  const ref = useRef<HTMLElement | null>(null);
  const isInView = useInView(ref, { once: true, amount: 0.2 });

  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    business: "",
    message: "",
    hearAbout: "",
    hearAboutOther: "",
  });

  const [showAlert, setShowAlert] = useState(false);
  const [phoneError, setPhoneError] = useState("");
  const [emailError, setEmailError] = useState("");
  const [nameError, setNameError] = useState("");
  const [hearAboutOtherError, setHearAboutOtherError] = useState("");
  const [isMessageAutoGenerated, setIsMessageAutoGenerated] = useState(false);

  const isValidEmail = (email: string) =>
    /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  const isValidName = (name: string) =>
    /^[a-zA-Z\s]+$/.test(name) && name.trim().length > 0;

  //   useEffect(() => {
  //     const handlePlanSelected = (event: CustomEvent) => {
  //       const { planName } = event.detail
  //       const autoMessage = getPlanMessage(planName)
  //
  //       if (autoMessage) {
  //         setFormData((prev) => ({
  //           ...prev,
  //           message: autoMessage,
  //         }))
  //         setIsMessageAutoGenerated(true)
  //       }
  //     }
  //
  //     window.addEventListener("planSelected", handlePlanSelected as EventListener)
  //     return () => {
  //       window.removeEventListener("planSelected", handlePlanSelected as EventListener)
  //     }
  //   }, [])

  //   const handleSubmit = async (e: React.FormEvent) => {
  //     e.preventDefault()
  //
  //     let hasErrors = false
  //     if (!isValidName(formData.name)) {
  //       setNameError("Name should contain only letters and spaces")
  //       hasErrors = true
  //     }
  //     if (formData.email && !isValidEmail(formData.email)) {
  //       setEmailError("Please enter a valid email address")
  //       hasErrors = true
  //     }
  //     if (formData.phone.length !== 10) {
  //       setPhoneError("Phone number must be exactly 10 digits")
  //       hasErrors = true
  //     }
  //     if (formData.hearAbout === "Other" && !formData.hearAboutOther.trim()) {
  //       setHearAboutOtherError("Please specify how you heard about us")
  //       hasErrors = true
  //     }
  //     if (hasErrors) return
  //
  //     try {
  //       const finalHearAboutValue =
  //         formData.hearAbout === "Other" ? formData.hearAboutOther.trim() : formData.hearAbout
  //
  //       // Submit to local SQL Server API
  //       await postLeadLocal({
  //         FullName: formData.name,
  //         EmailAddress: formData.email || "",
  //         PhoneNumber: formData.phone,
  //         BusinessName: formData.business || "",
  //         Message: formData.message,
  //         WhereDidYouHearAboutUs: finalHearAboutValue,
  //       })
  //
  //       setShowAlert(true)
  //       setFormData({
  //         name: "",
  //         email: "",
  //         phone: "",
  //         business: "",
  //         message: "",
  //         hearAbout: "",
  //         hearAboutOther: "",
  //       })
  //       setPhoneError("")
  //       setEmailError("")
  //       setNameError("")
  //       setHearAboutOtherError("")
  //       setIsMessageAutoGenerated(false)
  //     } catch (error) {
  //       console.error("Error submitting form:", error)
  //       alert("Something went wrong! Please try again.")
  //     }
  //   }

  const handleChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >
  ) => {
    const { name, value } = e.target;

    if (name === "name") {
      if (!/^[a-zA-Z\s]*$/.test(value)) return;
      setNameError("");
    }
    if (name === "email") setEmailError("");
    if (name === "phone") {
      if (!/^\d*$/.test(value)) return;
      if (value.length > 10) return;
      setPhoneError("");
    }
    if (name === "business" && !/^[a-zA-Z0-9\s&.,'-]*$/.test(value)) return;
    if (name === "hearAboutOther") setHearAboutOtherError("");
    if (name === "message" && isMessageAutoGenerated)
      setIsMessageAutoGenerated(false);

    setFormData({ ...formData, [name]: value });
  };
  // --- STYLES DEFINITION FOR SCREENSHOT MATCH ---

  // Updated placeholder color to explicitly be black (placeholder:text-black)
  const inputBaseClasses =
    "w-full text-base border-gray-200 bg-green-50/70 rounded-lg h-11 transition-all duration-300 p-2.5 text-gray placeholder:text-black";
  // Focus classes for the green border/ring
  const focusClasses =
    "focus:border-green-400 focus:ring-2 focus:ring-green-100 focus:outline-none";
  // Base classes for textarea
  const textareaBaseClasses =
    "w-full text-base min-h-[120px] border-gray-200 bg-green-50/70 rounded-lg resize-none transition-all duration-300 p-2.5 text-black placeholder:text-black";
  return (
    <section
      id="contact"
      ref={ref}
      className="py-8 sm:py-12 lg:py-16 xl:py-20 px-3 sm:px-4 lg:px-6 xl:px-20 bg-white relative"
    >
      <div className="max-w-7xl mx-auto text-center">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[rgb(6_182_212_/_0.1)] border border-[rgb(6_182_212_/_0.2)] backdrop-blur-sm mb-6">
          <PhoneCall className="w-4 h-4 text-cyan-600" />
          <span className="text-sm font-medium text-slate-700">Contact Us</span>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="text-center mb-12"
        >
          <h2 className="text-4xl lg:text-5xl font-bold mb-3">
            <span className="text-slate-900">Our </span>
            <span className="bg-gradient-to-r from-blue-600 to-cyan-500 bg-clip-text text-transparent">
              Get Started Today
            </span>
          </h2>

          <p className="text-lg text-slate-600">
            Ready to transform your Business? Contact us for a free demo and
            consultation.
          </p>
        </motion.div>

        {showAlert && (
          <div className="fixed inset-0 flex items-center justify-center bg-black/50 z-50 p-3 sm:p-4">
            <div className="bg-white rounded-xl shadow-lg max-w-sm sm:max-w-md w-full p-4 sm:p-6 relative text-center mx-4">
              <Button
                onClick={() => setShowAlert(false)}
                className="absolute top-2 right-2 sm:top-3 sm:right-3 text-gray-400 hover:text-gray-600"
              >
                <X className="w-4 h-4 sm:w-5 sm:h-5" />
              </Button>
              <h3 className="text-lg sm:text-xl font-bold text-primary mb-2 sm:mb-3">
                Informational Message
              </h3>
              <p className="text-sm sm:text-base text-gray-700">
                Thank you for your interest! We will contact you soon. <br />
                For further inquiry contact us on{" "}
                <span className="font-semibold text-primary">8149798679</span>.
              </p>
              <Button
                onClick={() => setShowAlert(false)}
                className="mt-4 sm:mt-6 bg-gradient-to-r from-primary to-primary-dark text-white px-4 sm:px-6 py-2 text-sm sm:text-base rounded-full"
              >
                OK
              </Button>
            </div>
          </div>
        )}

        <div className="flex flex-col lg:flex-row gap-6 sm:gap-8 lg:gap-12 items-start">
          {/* LEFT — CONTACT FORM */}

          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="w-full lg:w-1/2 order-2 lg:order-1"
          >
            <div className="bg-primary/5 border border-primary/20 rounded-xl sm:rounded-2xl p-4 sm:p-6 lg:p-8 shadow-lg">
              <h3 className="text-lg sm:text-xl lg:text-2xl font-bold text-gray-900 mb-4 sm:mb-6 text-left">
                Send us a Message
              </h3>

              <form className="space-y-4 sm:space-y-5 lg:space-y-6">
                {/* Name + Email */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  {/* Full Name */}
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                      Full Name *
                    </label>

                    <Input
                      name="name"
                      value={formData.name}
                      onChange={handleChange}
                      required
                      className={`${inputBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm ${
                        nameError ? "border-red-500" : ""
                      }`}
                      placeholder="Enter your full name"
                    />

                    {nameError && (
                      <p className="text-red-500 text-xs sm:text-sm mt-1">
                        {nameError}
                      </p>
                    )}
                  </div>

                  {/* Email */}
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                      Email Address
                    </label>

                    <Input
                      name="email"
                      type="email"
                      value={formData.email}
                      onChange={handleChange}
                      className={`${inputBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm ${
                        emailError ? "border-red-500" : ""
                      }`}
                      placeholder="Enter your email"
                    />

                    {emailError && (
                      <p className="text-red-500 text-xs sm:text-sm mt-1">
                        {emailError}
                      </p>
                    )}
                  </div>
                </div>

                {/* Phone + Business */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  {/* Phone */}
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                      Phone Number *
                    </label>

                    <Input
                      name="phone"
                      type="tel"
                      value={formData.phone}
                      onChange={handleChange}
                      required
                      className={`${inputBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm ${
                        phoneError ? "border-red-500" : ""
                      }`}
                      placeholder="Enter your phone number"
                    />

                    {phoneError && (
                      <p className="text-red-500 text-xs sm:text-sm mt-1">
                        {phoneError}
                      </p>
                    )}
                  </div>

                  {/* Business */}
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                      Business Name
                    </label>

                    <Input
                      name="business"
                      value={formData.business}
                      onChange={handleChange}
                      className={`${inputBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm`}
                      placeholder="Enter your business name"
                    />
                  </div>
                </div>

                {/* Hear About */}
                <div className="relative">
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                    Where did you hear about us? *
                  </label>

                  <select
                    name="hearAbout"
                    value={formData.hearAbout}
                    onChange={handleChange}
                    required
                    className="
    w-full text-xs sm:text-sm
    border border-gray-200 rounded-lg h-11
    transition-all duration-300 p-2 sm:p-2.5
    bg-green-50/70 text-black appearance-none
    placeholder:text-xs sm:placeholder:text-sm
  "
                  >
                    <option value="" hidden>
                      Select an option
                    </option>

                    {hearAboutOptions.map((option, idx) => (
                      <option key={idx} value={option}>
                        {option}
                      </option>
                    ))}
                  </select>

                  <svg
                    className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fillRule="evenodd"
                      d="M5.23 7.21a.75.75 0 011.06.02L10 10.94l3.71-3.71a.75.75 0 111.06 1.06l-4.25 4.25a.75.75 0 01-1.06 0L5.21 8.27a.75.75 0 01.02-1.06z"
                      clipRule="evenodd"
                    />
                  </svg>
                </div>

                {/* Other */}
                {formData.hearAbout === "Other" && (
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                      Other (please mention) *
                    </label>

                    <Input
                      name="hearAboutOther"
                      value={formData.hearAboutOther}
                      onChange={handleChange}
                      required
                      className={`${inputBaseClasses} ${focusClasses} placeholder:text-xs sm:placeholder:text-sm ${
                        hearAboutOtherError ? "border-red-500" : ""
                      }`}
                      placeholder="Enter details..."
                    />

                    {hearAboutOtherError && (
                      <p className="text-red-500 text-xs sm:text-sm mt-1">
                        {hearAboutOtherError}
                      </p>
                    )}
                  </div>
                )}

                {/* Message */}
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                    Message *
                  </label>

                  <Textarea
                    name="message"
                    value={formData.message}
                    onChange={handleChange}
                    required
                    className={`${textareaBaseClasses} ${focusClasses} text-xs sm:text-sm placeholder:text-xs sm:placeholder:text-sm`}
                    placeholder="Tell us about your requirements..."
                  />
                </div>

                {/* Submit */}
                <Button
                  type="submit"
                  className="w-full bg-gradient-to-r from-blue-600 to-emerald-500 hover:from-blue-700 hover:to-emerald-600 text-white py-2.5 sm:py-3 text-base sm:text-lg font-semibold rounded-lg shadow-lg transition-all duration-300"
                >
                  Send Message
                </Button>
              </form>
            </div>
          </motion.div>
          {/* RIGHT — CONTACT INFO */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="w-full lg:w-1/2 order-1 lg:order-2"
          >
            <div className="space-y-3 sm:space-y-4 lg:space-y-5">
              <div className="text-center">
                <h4 className="text-lg sm:text-xl lg:text-xl font-bold text-gray-900 mb-1 sm:mb-2">
                  Contact Information
                </h4>
              </div>

              {/* Phone, Email, Support */}
              <div className="grid grid-cols-3 gap-2 sm:gap-3 lg:gap-4">
                {MOCK_CONTACT.filter?.((item) =>
                  ["Phone", "Email", "Support Hours"].includes(item?.Title)
                )?.map?.((item) => {
                  let details: string[] = [];
                  try {
                    // <-- FIX: explicitly type the callback parameter 'd' to avoid implicit 'any'
                    details = (item.Details1 || "")
                      .split(",")
                      .map((d: string) => d.trim());
                  } catch {
                    details = item.Details1 ? [String(item.Details1)] : [];
                  }

                  const reorderedDetails =
                    details.length > 1
                      ? [details[details.length - 1], ...details.slice(0, -1)]
                      : details;

                  return (
                    <div
                      key={item.Id}
                      className="flex flex-col items-center text-center"
                    >
                      <div className="p-1.5 sm:p-2 rounded-full bg-primary-light flex items-center justify-center mb-1">
                        <item.Icon className="h-3 w-3 sm:h-4 sm:w-4" />
                      </div>
                      <h5 className="font-semibold text-gray-900 text-xs sm:text-xs mb-0.5">
                        {item.Title}
                      </h5>
                      <div className="text-gray-600 text-[10px] sm:text-xs">
                        {reorderedDetails.map((d: string, idx) => (
                          <p key={idx} className="leading-tight break-words">
                            {d}
                          </p>
                        ))}
                      </div>
                      {item.Details2 && (
                        <p className="text-[9px] sm:text-xs text-gray-500 mt-0.5 break-words">
                          {item.Details2}
                        </p>
                      )}
                    </div>
                  );
                })}
              </div>

              {/* Office */}
              <div className="bg-primary-light rounded-lg p-2 sm:p-2.5 shadow-sm">
                {MOCK_CONTACT.filter?.(
                  (item) => item?.Title === "Office"
                )?.map?.((item) => {
                  let offices: string[] = [];
                  try {
                    offices = JSON.parse(item.Details1);
                  } catch {
                    offices = [];
                  }

                  return (
                    <div key={item.Id}>
                      <div className="flex items-center justify-center mb-1.5 sm:mb-2">
                        <item.Icon className="h-3 w-3 sm:h-4 sm:w-4 mr-1" />
                        <h5 className="font-semibold text-gray-900 text-xs sm:text-sm">
                          Office Locations
                        </h5>
                      </div>

                      <div className="grid gap-1">
                        {offices.map((address, idx) => (
                          <div
                            key={idx}
                            className="bg-white rounded p-1.5 sm:p-2 border-l-2 sm:border-l-3 border-primary"
                          >
                            <div className="flex items-start">
                              <span className="inline-flex items-center justify-center w-3 h-3 sm:w-4 sm:h-4 bg-primary text-white rounded-full text-[8px] sm:text-[9px] font-semibold mr-1.5 mt-0.5 flex-shrink-0">
                                {idx + 1}
                              </span>
                              <p className="text-gray-700 text-[10px] sm:text-xs leading-tight break-words">
                                {address}
                              </p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Map */}
              <div className="bg-primary-light rounded-lg overflow-hidden shadow-md">
                {/* <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15036.51761826522!2d74.18727!3d19.57895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b887760ab19f%3A0x3fd52e46fe6d323f!2sSoulSoft%20Infotech!5e0!3m2!1sen!2sin!4v1758356538198!5m2!1sen!2sin%22
                    width="100%"
                    height="250"
                    style={{ border: "0" }}
                    allowFullScreen
                    loading="lazy"
                    referrerPolicy="no-referrer-when-downgrade"
                    className="rounded-lg sm:h-[300px] lg:h-[300px]"
                    title="SoulSoft Infotech Location"
                    /> */}
                <iframe
                  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15036.51761826522!2d74.18727!3d19.57895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b887760ab19f%3A0x3fd52e46fe6d323f!2sSoulSoft%20Infotech!5e0!3m2!1sen!2sin!4v1758356538198!5m2!1sen!2sin"
                  width="100%"
                  height="250"
                  style={{ border: "0" }}
                  allowFullScreen
                  loading="lazy"
                  referrerPolicy="no-referrer-when-downgrade"
                  className="rounded-lg sm:h-[300px] lg:h-[300px]"
                  title="SoulSoft Infotech Location"
                />
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
